### PR TITLE
Update to jobs_done10 1.3.1 and remove dependency on PyPI.

### PR DESCRIPTION
**Pull request by tarcisioe**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by tarcisioe** [comment]
@conda-forge-admin, please rerender

**Comment by nicoddemus** [comment]
Some tests are failing, looks like some version incompatibility?


https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=374721&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=504

**Comment by tarcisioe** [comment]
@nicoddemus looks like ElementTree.Element.getChildren was deprecated an has been removed in 3.9. Guess this needs fixing upstream. Should I limit this release to Python 3.8, or do I skip it and make a 1.3.1?

**Comment by tarcisioe** [comment]
@conda-forge-admin, please rerender

**Comment by tarcisioe** [comment]
Bumped to 1.3.1 which is Python 3.9 compatible.

**Review by nicoddemus — APPROVED** [review]

**Pull request merged**
